Machine Learning and Statistics

Winter 2023

by Ioan Domsa

***

## Task 1

***

> Square roots are difficult to calculate. In Python, you typically use the power operator (a double asterisk) or a package such
as `math`. In this task you should write a function `sqrt(x)` to approximate the square root of a floating point number x without
using the power operator or a package.

>Rather, you should use the Newton’s method. Start with an initial guess for the square root called $z_0$. You then repeatedly
improve it using the following formula, until the difference between some previous guess $z_{i}$ and the next $z_{i+1}$
is less than some threshold, say 0.01.

$$ z_{i+1} = z_i − \frac {z_i × z_i − x}{2z_i} $$


In [1]:
def sqrt(x):
    # Initial guess for the square root.
    z1 = x / 2.0
    # set a threshold of approximation
    t = 0.0000001
    # counter
    # c = 0

# Loop until we are accurate enough
    while True:
        # Newtons method
        z2 = z1 - ((z1*z1)-x)/(2*z1)
        # c = c + 1 
        # check the threshold
        if abs(z2-z1) <= t:
            break
        z1 = z2
    # return z2, c
    return z2

x = 3
# result, count = sqrt(x)
result = sqrt(x)
print(result)
# print(count)

1.7320508075688772


In [2]:
# Test function
sqrt(3)

1.7320508075688772

In [3]:
# Check Python's value for square root of 3
3**0.5

1.7320508075688772

### Notes

***

1. The calculation $ z^2 - x $ is exactly zero when $z$ is the sqare root of $x$. It is greater than zero when $z$ is too big. It is less than zero when $z$ is too small. Thus $(z^2 -x)^2$ is a good candidate for a cost function.

2. The derivative of the numerator $z^2 - x$ with respect to $z$ is $2z$. That is the denominator of the fraction in the formula from the question

***

## Task 2

***

> Consider the below contingency table based on a survey asking respondents whether they prefer coffee or tea and whether they prefer plain or chocolate biscuits.

>Use scipy.stats to perform a chi-squared test to see whether there is any evidence of an association between drink preference and biscuit preference in this instance.

|           	|            	|  **Biscuit** 	|              	|  
|:---------:	|:----------:	|:------------:	|:---------:	|  
|           	|            	| Chocolate     | Plain      	|  
| **Drink** 	| Coffee 	    |      43      	|     57    	|  
|           	| Tea  	        |      56      	|     45    	|  

In [4]:
# Data frames.
import pandas as pd

# Shuffles.
import random

# Statistics.
import scipy.stats as ss

In [5]:
# 43 coffee drinkers who preferred chocolate biscuit
coffee_choc = [["coffee", "chocolate"]] * 43

# Show
coffee_choc

[['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 

In [6]:
# 56 tea drinkers who preferred chocolate biscuit
tea_choc = [["tea", "chocolate"]] * 56

# Show
tea_choc

[['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'c

In [7]:
# 57 coffee drinkers who preferred plain biscuit
coffee_plain = [["coffee", "plain"]] * 57

# Show
coffee_plain

[['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee'

In [8]:
# 45 tea drinkers who preferred plain biscuit
tea_plain = [["tea", "plain"]] * 45

# Show
tea_plain

[['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['tea', 'plain']]

In [9]:
# Raw data, merge the four lists

raw_data = coffee_choc + coffee_plain + tea_choc + tea_plain

# show raw data
raw_data

[['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 

In [10]:
# Shuffle the data

random.shuffle(raw_data)

# show raw_data
raw_data

[['tea', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'plain'],
 ['tea', 'chocolate'],
 ['coffee', 'plain'],
 ['tea', 'plain'],
 ['tea', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'plain'],
 ['tea', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['coffee', 'chocolate'],
 ['tea', 'plain'],
 ['tea', 'chocolate'],
 ['coffee', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea', 'plain'],
 ['coffee', 'chocolate'],
 ['tea', 'chocolate'],
 ['coffee', 'plain'],
 ['tea', 'chocolate'],
 ['tea', 'chocolate'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['coffee', 'plain'],
 ['tea', 'plain'],
 ['coffee', 'plain'],
 ['tea', 'chocolate'],
 ['tea', 'plain'],
 ['coffee', 'chocolate'],
 ['tea', 'plain'],
 ['coffee', 'plain'],
 ['tea', 'plain'],
 ['coffee', 'plain'],
 ['tea', 'chocolate'],
 ['tea', 'plain'],
 ['tea', 'plain'],
 ['coffee', 'chocolate'],
 ['tea', 'chocolate'],
 ['tea'

In [11]:
# Zip the list - make the rows columns and the columns rows
# Interchange the outer and inner lists
drink, biscuit = list(zip(*raw_data))

# Show drink, biscuit
drink, biscuit

(('tea',
  'coffee',
  'coffee',
  'tea',
  'coffee',
  'tea',
  'tea',
  'coffee',
  'coffee',
  'tea',
  'coffee',
  'coffee',
  'coffee',
  'coffee',
  'coffee',
  'coffee',
  'coffee',
  'tea',
  'tea',
  'coffee',
  'tea',
  'tea',
  'coffee',
  'tea',
  'coffee',
  'tea',
  'tea',
  'coffee',
  'coffee',
  'coffee',
  'tea',
  'coffee',
  'tea',
  'tea',
  'coffee',
  'tea',
  'coffee',
  'tea',
  'coffee',
  'tea',
  'tea',
  'tea',
  'coffee',
  'tea',
  'tea',
  'tea',
  'tea',
  'coffee',
  'coffee',
  'tea',
  'coffee',
  'coffee',
  'tea',
  'tea',
  'tea',
  'tea',
  'tea',
  'tea',
  'coffee',
  'coffee',
  'tea',
  'coffee',
  'tea',
  'coffee',
  'coffee',
  'coffee',
  'coffee',
  'tea',
  'tea',
  'tea',
  'coffee',
  'coffee',
  'coffee',
  'tea',
  'coffee',
  'tea',
  'tea',
  'coffee',
  'coffee',
  'tea',
  'tea',
  'tea',
  'tea',
  'tea',
  'coffee',
  'coffee',
  'coffee',
  'tea',
  'tea',
  'tea',
  'coffee',
  'tea',
  'coffee',
  'tea',
  'tea',
  'coffee'

In [12]:
# create a data frame
df = pd.DataFrame({"drink": drink, "biscuit": biscuit})

# show
df

drink    biscuit
0       tea  chocolate
1    coffee  chocolate
2    coffee      plain
3       tea  chocolate
4    coffee      plain
..      ...        ...
196  coffee  chocolate
197  coffee  chocolate
198     tea  chocolate
199  coffee      plain
200  coffee  chocolate

[201 rows x 2 columns]

In [13]:
# perform cross tab contingency
cross = ss.contingency.crosstab(df["drink"], df["biscuit"])

# show
cross

CrosstabResult(elements=(array(['coffee', 'tea'], dtype=object), array(['chocolate', 'plain'], dtype=object)), count=array([[43, 57],
       [56, 45]]))

In [14]:
# The counts.
cross.count

array([[43, 57],
       [56, 45]])

In [15]:
# The first variable and the second

first, second = cross.elements

#show
first, second

(array(['coffee', 'tea'], dtype=object),
 array(['chocolate', 'plain'], dtype=object))

In [16]:
# Do the statistics.
result = ss.chi2_contingency(cross.count, correction = False)

# Show.
result

Chi2ContingencyResult(statistic=3.113937364324669, pvalue=0.07762509678333357, dof=1, expected_freq=array([[49.25373134, 50.74626866],
       [49.74626866, 51.25373134]]))

In [17]:
# The expected frequesncies if independent
result.expected_freq

array([[49.25373134, 50.74626866],
       [49.74626866, 51.25373134]])

In [18]:
# Preferd chocolate biscuits irespective of drink.
99 / 201

0.4925373134328358

In [19]:
# If no relationship between drink and biscuit, 
# then we should have same proportion of coffee drinkers
# liking chocolate biscuits as we have overall
100 * (99 / 201)

49.25373134328358

In [20]:
# If no relationship between drink and biscuit, 
# then we should have same proportion of peopple 
# liking plain biscuit who are tea drinkers as we have overall
102 * (101 / 201)

51.25373134328359

## Task 3

***

> Perform a t-test on the famous penguins data set to investigate 

> whether there is evidence of a significant difference in the body mass of male and female gentoo penguins.

In [21]:
# numerical arays
import numpy as np

In [22]:
# Load Penguins
df = pd.read_csv('notes/data/penguins.csv')

# Show
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
3            NaN     NaN  
4         3450.0  FEMALE  
..           ...     ...  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[344 rows x 7 columns]

In [23]:
# Gentoo male body mass

df_gentoo = df[df["species"] == "Gentoo"]

df_gentoo

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
220  Gentoo  Biscoe            46.1           13.2              211.0   
221  Gentoo  Biscoe            50.0           16.3              230.0   
222  Gentoo  Biscoe            48.7           14.1              210.0   
223  Gentoo  Biscoe            50.0           15.2              218.0   
224  Gentoo  Biscoe            47.6           14.5              215.0   
..      ...     ...             ...            ...                ...   
339  Gentoo  Biscoe             NaN            NaN                NaN   
340  Gentoo  Biscoe            46.8           14.3              215.0   
341  Gentoo  Biscoe            50.4           15.7              222.0   
342  Gentoo  Biscoe            45.2           14.8              212.0   
343  Gentoo  Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
220       4500.0  FEMALE  
221       5700.0    MALE  
222       4450.0  FEMALE  
223       5700.0    MALE  
224       5400.0    MALE  
..           ...     ...  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[124 rows x 7 columns]

In [24]:
# Gentoo Male mass
sample_male = df_gentoo.loc[df_gentoo['sex'] == 'MALE']['body_mass_g'].to_numpy()

count_sample_male = len(sample_male)
count_sample_male, sample_male

(61,
 array([5700., 5700., 5400., 5200., 5150., 5550., 5850., 5850., 6300.,
        5350., 5700., 5050., 5100., 5650., 5550., 5250., 6050., 5400.,
        5250., 5350., 5700., 4750., 5550., 5400., 5300., 5300., 5000.,
        5050., 5000., 5550., 5300., 5650., 5700., 5800., 5550., 5000.,
        5100., 5800., 6000., 5950., 5450., 5350., 5600., 5300., 5550.,
        5400., 5650., 5200., 4925., 5250., 5600., 5500., 5500., 5500.,
        5500., 5950., 5500., 5850., 6000., 5750., 5400.]))

In [25]:
# Gentoo Female mass
sample_female = df_gentoo.loc[df_gentoo['sex'] == 'FEMALE']['body_mass_g'].to_numpy()

count_sample_female = len(sample_female)
count_sample_female, sample_female

(58,
 array([4500., 4450., 4550., 4800., 4400., 4650., 4650., 4200., 4150.,
        4800., 5000., 4400., 5000., 4600., 4700., 5050., 5150., 4950.,
        4350., 3950., 4300., 4900., 4200., 5100., 4850., 4400., 4900.,
        4300., 4450., 4200., 4400., 4700., 4700., 4750., 5200., 4700.,
        4600., 4750., 4625., 4725., 4750., 4600., 4875., 4950., 4750.,
        4850., 4875., 4625., 4850., 4975., 4700., 4575., 5000., 4650.,
        4375., 4925., 4850., 5200.]))

In [26]:
# Perform t-test

ss.ttest_ind(sample_male, sample_female)

TtestResult(statistic=14.721676481405709, pvalue=2.133687602018886e-28, df=117.0)

> The t-test above sugests significant diference between the body mass of the two gender samples analysed.
> the statistic value of 14 shows a large difference between the means of the two samples.
> the small pvalue, close to 0 shows the probanility is very low

## Task 4

***

> Using the famous iris data set suggest whether the setosa class is easily separable from the other two classes.

> Provide evidence for your answer.

In [27]:
# Data frames.
import pandas as pd
# Machine Learning
import sklearn as sk
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [28]:
# Load iris data set
df = pd.read_csv('notes/data/iris.csv')
df = df.dropna()
# Show
df

sepal_length  sepal_width  petal_length  petal_width      class
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [29]:
# The X values
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']] 
# Show X
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [30]:
# y values.
y = df['class']
# Show
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: class, Length: 150, dtype: object

In [31]:
# Create a new instance of a classifier
clf = KNeighborsClassifier()
# Fit the data
clf.fit(X, y)

KNeighborsClassifier()

In [32]:
# Quick check that the classifier correctly predicts first X sample
clf.predict(X.iloc[:1])

array(['setosa'], dtype=object)

In [33]:
# The actual output for the first sample.
y.iloc[0]

'setosa'

In [34]:
# Keep some samples back for testing, train on the others.
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(X, y)
X_train

sepal_length  sepal_width  petal_length  petal_width
68            6.2          2.2           4.5          1.5
115           6.4          3.2           5.3          2.3
114           5.8          2.8           5.1          2.4
21            5.1          3.7           1.5          0.4
37            4.9          3.1           1.5          0.1
..            ...          ...           ...          ...
60            5.0          2.0           3.5          1.0
133           6.3          2.8           5.1          1.5
30            4.8          3.1           1.6          0.2
125           7.2          3.2           6.0          1.8
103           6.3          2.9           5.6          1.8

[112 rows x 4 columns]

In [35]:
# Training outputs.
y_train

68     versicolor
115     virginica
114     virginica
21         setosa
37         setosa
          ...    
60     versicolor
133     virginica
30         setosa
125     virginica
103     virginica
Name: class, Length: 112, dtype: object

In [36]:
# Create a new instance of a classifier.
clf = sk.neighbors.KNeighborsClassifier()

# Fit the data.
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [37]:
# Predict based on test set.
y_pred = clf.predict(X_test)
y_pred

array(['setosa', 'versicolor', 'virginica', 'virginica', 'setosa',
       'versicolor', 'setosa', 'versicolor', 'virginica', 'versicolor',
       'setosa', 'versicolor', 'setosa', 'versicolor', 'setosa',
       'virginica', 'setosa', 'virginica', 'setosa', 'versicolor',
       'virginica', 'setosa', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'setosa', 'versicolor',
       'setosa', 'versicolor', 'setosa', 'virginica', 'virginica',
       'virginica', 'versicolor', 'versicolor'], dtype=object)

In [38]:
# Proportion of correct classifications on test set.
(clf.predict(X_test) == y_test).sum() / X_test.shape[0]

0.868421052631579

In [39]:
y_test == 'setosa'

35      True
66     False
72     False
141    False
32      True
106    False
12      True
52     False
102    False
98     False
34      True
73     False
2       True
58     False
26      True
140    False
17      True
70     False
25      True
92     False
130    False
10      True
97     False
63     False
105    False
132    False
83     False
134    False
29      True
82     False
4       True
61     False
49      True
145    False
148    False
117    False
85     False
54     False
Name: class, dtype: bool

In [40]:
y_pred == 'setosa'

array([ True, False, False, False,  True, False,  True, False, False,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False, False,  True, False, False, False, False, False,
       False,  True, False,  True, False,  True, False, False, False,
       False, False])

In [41]:
setosa_test = (y_test == 'setosa')
setosa_test.sum()

12

In [42]:
setosa_pred = (y_pred == 'setosa')
setosa_pred.sum()

12

In [43]:
# Calculate proportion to understand if setosa is easily separable from other classes 
setosa_acc = setosa_test.sum() / setosa_pred.sum()
setosa_acc

1.0

***
## End
